services:
  db:
    container_name: mysql_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./sql/db-create.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local