app:
  connect-timeout: 1000
  read-timeout: 2000
  base-url: https://www.yuriytkach.com
  s3-bucket: my-bucket
  s3-region: us-east-1

info:
  app:
    name: 'Excel Uploading App'
    description: 'Super cool app!'
  author: 'Myself :)'

management:
  endpoint:
    info.enabled: true
    metrics.enabled: true
    health:
      probes.enabled: true
      show-details: always
  info.env.enabled: true
  endpoints:
    web:
      exposure.include: 'info,health,metrics'

spring:
  servlet:
    multipart:
      max-file-size: 10MB

server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: test

server:
  shutdown: immediate